name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
   
     
    # Run tests
    - name: Test
      run: dotnet test

    # Generate the website
    - name: Publish
      run: dotnet publish test2.csproj --configuration Release
    # Publish the website
    - name: GitHub Pages action
      
      uses: peaceiris/actions-gh-pages@v3.6.4
      with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            publish_branch: master
            force_orphan: true
    
