name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    # Setup .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
     
    - name: Publish with dotnet
      run: dotnet publish --configuration Release --output build
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.2
      
